export const atlasData: Record<string, string[]> = {
    "umbilicalCord:normal": ["normal-uc", "normal-umbilical-cord"],
    "membranes:normal": [
        "normal-chorionic-plate",
        "normal-chorionic-plate-2",
        "normal-chorion",
        "normal-membranes-low",
        "normal-membranes-med",
        "normal-membranes-high",
    ],
    "placentalVilli:normal": [
        "normal-term-villi",
        "normal-term-villi-high",
        "normal-villi-1st-trimester",
        "normal-villi-2nd-trimester",
        "normal-villi-2nd-trimester-high",
        "normal-villi-5-weeks",
        "normal-villi-5-weeks-2",
        "normal-villi-8-weeks",
    ],
    "maternalDecidua:normal": ["normal-basal-plate", "normal-basal-plate-2"],
    "maternalDecidua:basal-plate-myometrial-fibers": ["basal-plate-myometrial-fibers--bpmf-stage-2-2", "basal-plate-myometrial-fibers--bpmf-stage-1-2", "basal-plate-myometrial-fibers--bpmf-stage-1", "basal-plate-myometrial-fibers--bpmf-stage-2-3", "basal-plate-myometrial-fibers--bpmf-stage-2-desmin", "basal-plate-myometrial-fibers--bpmf-stage-2"],
    "maternalDecidua:decidual-arteriopathy": ["maternal-vascular-malperfusion--chronic-perivasculitis-arteriopathy", "maternal-vascular-malperfusion--decidual-arteriopathy-fibrinoid-necrosis", "maternal-vascular-malperfusion--decidual-arteriopathy-mural-hypertrophy-2", "maternal-vascular-malperfusion--decidual-arteriopathy-mural-hypertrophy", "maternal-vascular-malperfusion--decidual-arteriopathy-1", "maternal-vascular-malperfusion--decidual-arteriopathy-2"],
    "maternalDecidua:lymphoplasmacytic-deciduitis": ["chronic-inflammatory-lesions--lymphoplasmacytic-deciduitis-2", "chronic-inflammatory-lesions--lymphoplasmacytic-deciduitis", "chronic-inflammatory-lesions--plasma-cell-deciduitis-2", "chronic-inflammatory-lesions--plasma-cell-deciduitis"],
    "membranes:acute-chorioamnionitis": ["acute-chorioamnionitis--acute-chorioamnionitis-grade-2-mir-2", "acute-chorioamnionitis--acute-chorioamnionitis-grade-2-mir", "acute-chorioamnionitis--acute-chorioamnionitis-stage-2-mir"],
    "membranes:acute-chorionitis": ["acute-chorioamnionitis--acute-chorioamnionitis-stage-1-mir-2", "acute-chorioamnionitis--acute-chorioamnionitis-stage-1-mir"],
    "membranes:acute-subchorionitis": ["acute-chorioamnionitis--acute-chorioamnionitis-stage-1-mir-subchorionitis"],
    "membranes:chorioamniotic-hemosiderosis": ["abruption--chorioamnionitic-hemosiderosis", "abruption--chorioamniotic-hemosiderosis"],
    "membranes:chorionic-histiocytic-hyperplasia": ["chronic-inflammatory-lesions--chorionic-histiocytic-hyperplasia-2", "chronic-inflammatory-lesions--chorionic-histiocytic-hyperplasia"],
    "membranes:chorionic-vasculitis": ["acute-chorioamnionitis--acute-chorioamnionitis-stage-1-fir-in-vein", "acute-chorioamnionitis--acute-chorioamnionitis-stage-1-fir"],
    "membranes:chronic-chorioamnionitis": ["chronic-inflammatory-lesions--chronic-chorioamnionitis-2", "chronic-inflammatory-lesions--chronic-chorioamnionitis"],
    "membranes:pigment-laden-macrophages": ["miscellaneous-lesions--membranous-pigment-laden-macrophages-2", "miscellaneous-lesions--membranous-pigment-laden-macrophages-3", "miscellaneous-lesions--membranous-pigment-laden-macrophages"],
    "placentalVilli:accelerated-villous-maturation": ["maternal-vascular-malperfusion--accelerated-villous-maturation-1", "maternal-vascular-malperfusion--accelerated-villous-maturation-2", "maternal-vascular-malperfusion--accelerated-villous-maturation-3"],
    "placentalVilli:avascular-villi": ["fetal-vascular-malperfusion--avascular-villi-2", "fetal-vascular-malperfusion--avascular-villi-3", "fetal-vascular-malperfusion--avascular-villi"],
    "placentalVilli:basal-chronic-villitis": ["chronic-inflammatory-lesions--basal-villitis", "chronic-inflammatory-lesions--basal-villits"],
    "placentalVilli:chorangioma": ["villous-and-perivillous-changes--chorangioma-2", "villous-and-perivillous-changes--chorangioma-with-infarction-changes", "villous-and-perivillous-changes--chorangioma"],
    "placentalVilli:chorangiomatosis": ["villous-and-perivillous-changes--chorangiomatosis-2", "villous-and-perivillous-changes--chorangiomatosis"],
    "placentalVilli:chorangiosis": ["villous-and-perivillous-changes--chorangiosis-2", "villous-and-perivillous-changes--chorangiosis-3", "villous-and-perivillous-changes--chorangiosis"],
    "placentalVilli:chronic-histiocytic-intervillositis": ["villous-and-perivillous-changes--chronic-histiocytic-inflammation-cd68", "villous-and-perivillous-changes--chronic-histiocytic-inflammation", "villous-and-perivillous-changes--chronic-histiocytic-intervillositis"],
    "placentalVilli:delayed-villous-maturation": ["villous-and-perivillous-changes--delayed-villous-maturation"],
    "placentalVilli:distal-villous-hypoplasia": ["maternal-vascular-malperfusion--distal-villous-hypoplasia-2", "maternal-vascular-malperfusion--distal-villous-hypoplasia-3", "maternal-vascular-malperfusion--distal-villous-hypoplasia"],
    "placentalVilli:eosinophilic-t-cell-vasculitis": ["chronic-inflammatory-lesions--eosinophilic-t-cell-chorionic-vasculitis-2", "chronic-inflammatory-lesions--eosinophilic-t-cell-chorionic-vasculitis-thrombus", "chronic-inflammatory-lesions--eosinophilic-t-cell-chorionic-vasculitis"],
    "placentalVilli:fetal-vessel-thrombosis": ["fetal-vascular-malperfusion--non-occlusive-thrombus-with-calc", "fetal-vascular-malperfusion--non-occlusive-thrombus", "fetal-vascular-malperfusion--occlusive-thrombus-2", "fetal-vascular-malperfusion--occlusive-thrombus-and-involution", "fetal-vascular-malperfusion--occlusive-thrombus"],
    "placentalVilli:high-grade-chronic-villitis": ["chronic-inflammatory-lesions--chronic-villitis-figure", "chronic-inflammatory-lesions--chronic-villitis-high-grade"],
    "placentalVilli:increased-fetal-nrbcs": ["villous-and-perivillous-changes--increased-fetal-nrbcs"],
    "placentalVilli:infarction-hematoma": ["maternal-vascular-malperfusion--infarction-hematoma-2", "maternal-vascular-malperfusion--infarction-hematoma-3", "maternal-vascular-malperfusion--infarction-hematoma"],
    "placentalVilli:intervillous-thrombus": ["villous-and-perivillous-changes--intervillous-thrombus-2", "villous-and-perivillous-changes--intervillous-thrombus-3", "villous-and-perivillous-changes--intervillous-thrombus"],
    "placentalVilli:intramural-fibrin-deposition": ["fetal-vascular-malperfusion--intramural-fibrin-deposition-2", "fetal-vascular-malperfusion--intramural-fibrin-deposition-recent-and-remote", "fetal-vascular-malperfusion--intramural-fibrin-deposition"],
    "placentalVilli:intravillous-hemorrhage": ["abruption--intravillous-hemorrhage-2", "abruption--intravillous-hemorrhage-3", "abruption--intravillous-hemorrhage"],
    "placentalVilli:low-grade-chronic-villitis": ["chronic-inflammatory-lesions--chronic-villitis-low-grade-2", "chronic-inflammatory-lesions--chronic-villitis-low-grade-3", "chronic-inflammatory-lesions--chronic-villitis-low-grade"],
    "placentalVilli:massive-perivillous-fibrin": ["villous-and-perivillous-changes--maternal-perivillous-fibrin-deposition-high", "villous-and-perivillous-changes--maternal-perivillous-fibrin-deposition-low", "gross-images--mpfvd-cut-surface", "gross-images--mpfvd-maternal-surface"],
    "placentalVilli:patchy-villous-edema": ["villous-and-perivillous-changes--patchy-villous-edema-2", "villous-and-perivillous-changes--patchy-villous-edema"],
    "placentalVilli:perivillous-fibrin-plaque": ["villous-and-perivillous-changes--perivillous-fibrin-plaque"],
    "placentalVilli:remote-marginal-hematoma": ["abruption--recent-marginal-retroplacental-hematoma"],
    "placentalVilli:retroplacental-hematoma": ["abruption--recent-marginal-retroplacental-hematoma", "abruption--retroplacental-hematoma-with-infarction-2", "abruption--retroplacental-hematoma-with-infarction"],
    "placentalVilli:sickled-red-blood-cells": ["villous-and-perivillous-changes--intervillous-sickle-cells"],
    "placentalVilli:stem-vessel-obliteration": ["fetal-vascular-malperfusion--stem-vessel-obliteration-2", "fetal-vascular-malperfusion--stem-vessel-obliteration-3", "fetal-vascular-malperfusion--stem-vessel-obliteration"],
    "placentalVilli:villous-agglutination": ["maternal-vascular-malperfusion--villous-agglutination-2", "maternal-vascular-malperfusion--villous-agglutination"],
    "placentalVilli:villous-infarct": ["maternal-vascular-malperfusion--villous-infarct", "maternal-vascular-malperfusion--villous-infarction-high", "maternal-vascular-malperfusion--villous-infarction-low"],
    "placentalVilli:villous-stromal-vascular-karyorrhexis": ["fetal-vascular-malperfusion--stromal-villous-karyorrhexis-2", "fetal-vascular-malperfusion--stromal-villous-karyorrhexis-3", "fetal-vascular-malperfusion--stromal-villous-karyorrhexis"],
    "umbilicalCord:meconium-associated-vascular-necrosis": ["miscellaneous-lesions--meconium-related-vascular-necrosis-2", "miscellaneous-lesions--meconium-related-vascular-necrosis"],
    "umbilicalCord:necrotizing-funisitis": ["acute-chorioamnionitis--acute-chorioamnionitis-stage-3-fir"],
    "umbilicalCord:umbilical-arteritis": ["acute-chorioamnionitis--acute-chorioamnionitis-stage-2-fir-2", "acute-chorioamnionitis--acute-chorioamnionitis-stage-2-fir"],
    "umbilicalCord:umbilical-phlebitis": ["acute-chorioamnionitis--acute-chorioamnionitis-stage-1-fir-in-vein", "acute-chorioamnionitis--acute-chorioamnionitis-stage-1-fir"],
};
