"use client";

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { ShieldAlert } from "lucide-react";

export function DisclaimerModal() {
  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="outline">
          <ShieldAlert className="mr-2" />
          Disclaimer
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[625px]">
        <DialogHeader>
          <DialogTitle className="font-headline text-2xl">Disclaimer &amp; License</DialogTitle>
          <DialogDescription>
            Please read the following terms before using this tool.
          </DialogDescription>
        </DialogHeader>
        <div className="grid gap-6 py-4 text-sm text-foreground/90 max-h-[70vh] overflow-y-auto pr-2">
          <div className="space-y-2">
            <h3 className="font-bold">Free to Use</h3>
            <p>
              This application is provided free of charge for educational and clinical reference purposes.
            </p>
          </div>

          <div className="space-y-2">
            <h3 className="font-bold">Copyright &amp; Ownership</h3>
            <p>
              This application, including its underlying source code, design, and all images from the
              placental atlas, is the copyrighted property of the{" "}
              <span className="font-semibold">Society for Pediatric Pathology (SPP)</span>.
            </p>
            <p>
              The codebase, images, and overall style may not be copied, reproduced, distributed, or
              modified without the prior written consent of the SPP.
            </p>
          </div>

          <div className="space-y-2">
            <h3 className="font-bold">Permitted Use of Images</h3>
            <p>
              Photographs from the atlas that retain the SPP watermark may be used in presentations,
              provided they are not altered or reproduced without the watermark. Images may{" "}
              <span className="font-semibold">not</span> be used in publications of any kind without
              written permission from the SPP.
            </p>
          </div>

          <div className="space-y-2">
            <h3 className="font-bold">No Warranty &amp; Accuracy</h3>
            <p>
              The SPP does not guarantee the absolute accuracy, completeness, or reliability of any
              output generated by this application. All generated content should be carefully reviewed
              and verified by a qualified pathologist.
            </p>
            <p className="font-semibold">
              It is the sole responsibility of the user to ensure the accuracy and appropriateness of
              the generated output before clinical or diagnostic use.
            </p>
          </div>

          <div className="space-y-2">
            <h3 className="font-bold">No Medical or Legal Advice</h3>
            <p>
              This tool is intended to assist with standardized reporting and does not constitute
              medical, legal, or professional advice. It is not a substitute for the independent
              judgment of a licensed medical professional.
            </p>
          </div>

          <div className="space-y-2">
            <h3 className="font-bold">Limitation of Liability</h3>
            <p>
              To the fullest extent permitted by law, the Society for Pediatric Pathology shall not be
              liable for any direct, indirect, incidental, consequential, or special damages arising out
              of or in connection with the use of, or inability to use, this application or its output.
            </p>
          </div>

          <div className="space-y-2">
            <h3 className="font-bold">Acceptance of Terms</h3>
            <p>
              By using this application, you acknowledge that you have read, understood, and agree to be
              bound by these terms. If you do not agree, please discontinue use of the application.
            </p>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
